# 数据库配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/chac?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: stephen946784
        driver-class-name: com.mysql.cj.jdbc.Driver

    # JPA配置
    jpa:
        hibernate:
            ddl-auto: update  # 自动更新数据库表结构
        show-sql: true      # 显示SQL语句
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true

# 服务器配置
server:
    port: 8080

# 日志配置
logging:
    level:
        com.chac: DEBUG
        org.springframework.web: DEBUG